@{
    PSDependOptions                                   = @{
        AddToPath  = $true
        Target     = 'output\RequiredModules'
        Parameters = @{
            Repository      = 'PSGallery'
            AllowPreRelease = $true
        }
    }

    InvokeBuild                                       = 'latest'
    PSScriptAnalyzer                                  = 'latest'
    Pester                                            = 'latest'
    Plaster                                           = 'latest'
    ModuleBuilder                                     = 'latest'
    ChangelogManagement                               = 'latest'
    Sampler                                           = 'latest'
    'Sampler.GitHubTasks'                             = 'latest'
    PowerShellForGitHub                               = 'latest'
    'Sampler.DscPipeline'                             = 'latest'
    MarkdownLinkCheck                                 = 'latest'
    'DscResource.AnalyzerRules'                       = 'latest'
    DscBuildHelpers                                   = 'latest'
    Datum                                             = 'latest'
    ProtectedData                                     = 'latest'
    'Datum.ProtectedData'                             = 'latest'
    'Datum.InvokeCommand'                             = 'latest'
    Configuration                                     = 'latest'
    Metadata                                          = 'latest'
    xDscResourceDesigner                              = 'latest'
    'DscResource.Test'                                = 'latest'
    #'Microsoft.PowerShell.SecretManagement'           = 'latest'

    # Composites
    #'DscConfig.M365'                                  = '0.2.0'
    'DscConfig.Demo'                                  = '0.8.2'

    # Azure
    'Az.KeyVault'                                     = 'latest'
    'Az.Resources'                                    = 'latest'
    'Az.Accounts'                                     = 'latest'

    #DSC Resources
    xPSDesiredStateConfiguration                      = '9.1.0'
    ComputerManagementDsc                             = '8.5.0'
    NetworkingDsc                                     = '8.2.0'
    JeaDsc                                            = '0.7.2'
    xWebAdministration                                = '3.2.0'
    FileSystemDsc                                     = '1.1.1'
    SecurityPolicyDsc                                 = '2.10.0.0'
    xDscDiagnostics                                   = '2.8.0'

    Microsoft365DSC                                   = '1.23.607.1'

    # Required for Microsoft365DSC. This section is generated by running the following command:
    # Update-M365DSCDependencies -ValidateOnly | ForEach-Object { [pscustomobject]$_ }  | ForEach-Object { "'{0}' = '{1}'" -f $_.ModuleName, $_.RequiredVersion } | Set-Clipboard
    # (Import-PowerShellDataFile -Path '.\output\RequiredModules\Microsoft365DSC\*\Dependencies\Manifest.psd1').Dependencies | ForEach-Object { "'{0}' = '{1}'" -f $_.ModuleName, $_.RequiredVersion } | Set-Clipboard
    'DSCParser'                                       = '1.3.0.9'
    'ExchangeOnlineManagement'                        = '3.1.0'
    'Microsoft.Graph.Applications'                    = '1.27.0'
    'Microsoft.Graph.Authentication'                  = '1.27.0'
    'Microsoft.Graph.DeviceManagement'                = '1.27.0'
    'Microsoft.Graph.DeviceManagement.Administration' = '1.27.0'
    'Microsoft.Graph.DeviceManagement.Enrolment'      = '1.27.0'
    'Microsoft.Graph.Devices.CorporateManagement'     = '1.27.0'
    'Microsoft.Graph.Groups'                          = '1.27.0'
    'Microsoft.Graph.Identity.DirectoryManagement'    = '1.27.0'
    'Microsoft.Graph.Identity.Governance'             = '1.27.0'
    'Microsoft.Graph.Identity.SignIns'                = '1.27.0'
    'Microsoft.Graph.Planner'                         = '1.27.0'
    'Microsoft.Graph.Teams'                           = '1.27.0'
    'Microsoft.Graph.Users'                           = '1.27.0'
    'Microsoft.Graph.Users.Actions'                   = '1.27.0'
    'Microsoft.PowerApps.Administration.PowerShell'   = '2.0.166'
    'MicrosoftTeams'                                  = '5.2.0'
    'MSCloudLoginAssistant'                           = '1.0.111'
    'PnP.PowerShell'                                  = '1.12.0'
    'ReverseDSC'                                      = '2.0.0.15'

}
